### ISSUE TITLE
Error while cloning into mucache

### ISSUE THREAD

**Issue by deerlove-lxq** [eniac/mucache#1]
Something went wrong while cloning, please check the invalid path.
```
Cloning into 'mucache'...
remote: Enumerating objects: 450, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 450 (delta 7), reused 23 (delta 6), pack-reused 426
Receiving objects: 100% (450/450), 27.75 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (83/83), done.
error: invalid path 'experiments/boutique/data/currency_conversion.json:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by Mellonta** [comment]
It seems that it panics because Windows doesn’t support colons in the filename. As I don't have a Windows PC, I can't test it myself. Could you try downloading the repo zip directly?

**Comment by angelhof** [comment]
Maybe the latest commit (that removes this and other such files) fixes the issue for you @deerlove-lxq ?

**Comment by deerlove-lxq** [comment]
The issue is fixed! Thanks for solving my problem! 
By the way, could you please share the paper's ppt for NSDI '24?
